# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Genetic Fractals
tagline:          '2D genetic fractals maker’s guide'
description:      'GitHub Page in Jekykll for Genetic Fractals studies by Henk Mulder'
url:              http://RadW2020.github.io/GeneticFractal2D-1/
baseurl:          http://RadW2020.github.io/GeneticFractal2D-1/

author:
  name:           'Genetic Fractals'
  url:            https://geneticfractals.org
paginate:         5

# Custom vars
version:          2.1.0
gems:             [jekyll-paginate]

github:           'GeneticFractals'
